---
- name: Create directories for extended configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/ssh_config.d
    - /etc/sshd_config.d

- name: Ensure extended configs are included
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "Include {{ item }}.d/*.conf"
  loop:
    - /etc/ssh/ssh_config
    - /etc/ssh/sshd_config

- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: client.conf, dest: /etc/ssh/ssh_config.d/hardened_ssh_client.conf }
    - { src: server.conf, dest: /etc/ssh/sshd_config.d/hardened_ssh_server.conf }
  notify:
    - Restart sshd
